server:
    port: 8080

mdm:
# Setup proxy if working on EU laptop
# Pass user name/password values as parameters to store it in a file
    proxy:
        enable: true
        # host: psbru.ec.europa.eu
        # port: 8012
        user:
            name: greulla
            password: Pipeau1.

spring:
    datasource:
        # See README.md on how to use environment variables
        # OR hardcode them here but do not commit this file if you uncomment:
        username: lg
        password: mercredi