version: "3.8"

services:
  mdd:
    container_name: mdd
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ${SQL_DIR}:/docker-entrypoint-initdb.d
      - ${MYSQL_CONF_DIR}:/etc/mysql/conf.d
      - ${HOME}/db_data/mdd:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: tedcvsrepo
      MYSQL_ROOT_PASSWORD: tedefo
      MYSQL_USER: tedefo
      MYSQL_PASSWORD: tedefo
    expose:
      - "3306"
    healthcheck:
      test: "mysqladmin -h$$(hostname -i) -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} status &>/dev/null"
      interval: 10s
      retries: 15
